# Target device
MCU = atmega644p
F_CPU = 8000000
LFUSE = 0xE2
HFUSE = 0xDA
EFUSE = 0xFD

# Application files and targets
TARGET = dds

# Place -I options here
CINCS = 
CXXINCS = 

# Place extra C/CXX arguments here
CEXTRA = 
CXXEXTRA = 

# Source files for C compiler
SRC = memory.c bandplan.c main.c lang.c lcd.c

# Source files for C++ compiler
CXXSRC = 

# Source files in assembly
ASRC =

# Extra libraries
LDEXTRA = -lm

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.avr.inc
-include ~/.gEDA/Makefile.avr.inc
